CREATE DATABASE IF NOT EXISTS threatintel CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE threatintel;

CREATE TABLE IF NOT EXISTS threats (
  id BIGINT NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  severity VARCHAR(16) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

